---
cssPath:
  default: 
    - https://golden-layout.com/files/latest/css/goldenlayout-base.css
    - https://cdn3.devexpress.com/jslib/20.1.3/css/dx.common.css
    - ./assets/softtech-theme.css
    - https://golden-layout.com/files/latest/css/goldenlayout-light-theme.css
    - https://cdn3.devexpress.com/jslib/20.1.3/css/dx.light.css
  compact: 
    - https://golden-layout.com/files/latest/css/goldenlayout-base.css
    - https://cdn3.devexpress.com/jslib/20.1.3/css/dx.common.css
    - ./assets/softtech-theme.css
    - https://golden-layout.com/files/latest/css/goldenlayout-light-theme.css
    - https://cdn3.devexpress.com/jslib/20.1.3/css/dx.light.compact.css
  dark:
    - https://golden-layout.com/files/latest/css/goldenlayout-base.css
    - https://cdn3.devexpress.com/jslib/20.1.3/css/dx.common.css
    - ./assets/softtech-theme.css
    - https://golden-layout.com/files/latest/css/goldenlayout-dark-theme.css
    - https://cdn3.devexpress.com/jslib/20.1.3/css/dx.dark.css
  dark-compact:
    - https://golden-layout.com/files/latest/css/goldenlayout-base.css
    - https://cdn3.devexpress.com/jslib/20.1.3/css/dx.common.css
    - ./assets/softtech-theme.css
    - https://golden-layout.com/files/latest/css/goldenlayout-dark-theme.css
    - https://cdn3.devexpress.com/jslib/20.1.3/css/dx.dark.compact.css


regionalDefinition:
  - region: tr
    devExLocaleCDNAddress: https://cdn3.devexpress.com/jslib/21.2.3/js/localization/dx.messages.tr.js
singleTab: true